/* Cuda (and host!) debug functions */
__host__ void dbg_print_deldop_fit_host(struct dat_t *ddat, int s, int f, const char *filename);
__host__ void dbg_print_deldop_fit_host2(struct deldopfrm_t *frame, const char *filename_fit);
__host__ void dbg_print_fit_host(struct dat_t *ddat, int s, int f, const char *filename);
__host__ void dbg_print_fit(struct dat_t *ddat, int s, int f, const char *filename, int gpuid);
__host__ void dbg_print_deldop_fit(struct dat_t *ddat, int s, int , const char *filename);
__host__ void dbg_print_array(float *data, int x, int y);
__host__ void dbg_print_array1D(float *data, int size);
__host__ void dbg_print_array1(float *in, int size);
__host__ void dbg_print_array1D_dbl(double *data, int size, int offset, const char *filename);
__host__ void dbg_print_lghtcrv_arrays(struct dat_t *ddat, int set, int n, const char *filename);
__host__ void dbg_print_lghtcrv_arrays_host(struct lghtcrv_t *lghtcrv, int set, int n, const char *filename);
__host__ void dbg_print_lghtcrv_xyy2(struct dat_t *ddat, int set, int ncalc, const char *filename);
__host__ void dbg_print_lghtcrv_xyy2_host(struct lghtcrv_t *lghtcrv, int set, int ncalc, const char *filename);
__host__ void dbg_print_lghtcrv_pos_arrays(struct dat_t *ddat, int set, int f, int npixels, int n);
__host__ void dbg_print_lghtcrv_pos_arrays_host(struct lghtcrv_t *lghtcrv, int f, int set);
__host__ void dbg_print_pos_arrays2(struct pos_t **pos, int f, int npixels, int n);
__host__ void dbg_print_pos_arrays2_host(struct pos_t *pos);
__host__ void dbg_print_pos_arrays_full32(struct pos_t **pos, int f, int npixels, int n);
__host__ void dbg_print_pos_arrays_full64(struct pos_t **pos, int f, int npixels, int n);
__host__ void dbg_print_pos_arrays_full_host(struct pos_t *pos);
__host__ void dbg_print_facet_normals_host(struct mod_t *mod, const char *fn);
__host__ void dbg_print_facet_normals(struct mod_t *dmod, int nf, const char *fn);
__host__ void dbg_print_facet_normals_dbl3(double3 *normals, int nf, const char *fn);
__host__ void dbg_print_pos_bd(struct pos_t **pos, int f, int npixels, int n);
__host__ void dbg_print_lc_fit(struct dat_t *ddat, int s, const char *filename_fit, int n);
__host__ void dbg_print_lc_fit_host(struct lghtcrv_t *lghtcrv, const char *filename_fit, int n);
__host__ void dbg_print_pos_z_host(struct pos_t *pos, const char *fn);
